### PR TITLE
docs: flock formula is now in homebrew-core

### PR DESCRIPTION
**Pull request by hakamadare**

### CODE REVIEW

**Comment by josephholsten** [comment]
Thanks! Also, yay!

**Comment by heated** [comment]
It's not though at least as of today?
```
$ brew info homebrew/cask/flock
flock: 2.2.509
https://flock.com/
/opt/homebrew/Caskroom/flock/2.2.509 (3,539 files, 218MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/flock.rb
==> Name
Flock
==> Description
Business messaging and team collaboration app
```

**Comment by josephholsten** [comment]
it’s not a cask, just a regular formula:
http://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/flock.rb

**Comment by heated** [comment]
I did `$ brew install flock` and the "Business messaging and team collaboration app" was installed rather than this tool. Do you know why that might be?

**Comment by heated** [comment]
```
$ brew uninstall flock
Warning: Treating flock as a formula. For the cask, use homebrew/cask/flock
Uninstalling /opt/homebrew/Cellar/flock/0.4.0... (6 files, 61.0KB)

$ brew untap discoteq/discoteq
Untapping discoteq/discoteq...
Untapped 1 formula (14 files, 9.9KB).

$ brew info flock
flock: 2.2.509
https://flock.com/
/opt/homebrew/Caskroom/flock/2.2.509 (3,539 files, 218MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/flock.rb
==> Name
Flock
==> Description
Business messaging and team collaboration app
...
```

**Comment by heated** [comment]
Ah nvm, I just never update homebrew.

**Pull request merged**
