### PR TITLE
-c behaviour should be like in linux flock

### PR DESCRIPTION
**Pull request by newffy**

### CODE REVIEW

**Comment by josephholsten** [comment]
Implementation looks fine, but I’m reluctant to add it because I don’t see the value besides for compatibility. I’d rather solve this with documentation than code with potential bugs and maintenance burden. 

That said, there’s been a few requests for this. If someone else wants to endorse this, I can live with it.

Probably needs tests and doc.

**Comment by hbouhadji** [comment]
I suppose there is no news about this ?

**Comment by newffy** [comment]
> I suppose there is no news about this ?

I still stand for compatibility and will be glad if PR will be merged once (can improve it if the author decide to merge it)

**Comment by josephholsten** [comment]
Sounds like there's more than one person who wants this, so I'll merge. Thanks!

**Comment by josephholsten** [comment]
Released in https://github.com/discoteq/flock/releases/tag/v0.4.0

**Pull request merged**
